pack:
    meta:
        write: true
        # The resource-pack icon (in the plugin folder)
        icon: 'icon.png'
        # The resource-pack description
        description: 'Custom server pack'
    # How to generate the resource pack
    # -> file:filename
    #     -> Generates a resource pack as a file (ZIP)
    # -> mergezipfile:filename
    #     -> Similar to file:filename but if the file exists,
    #        it will merge the contents instead of overwriting
    #        them (ZIP)
    # -> upload:authorization:url
    #     -> Uploads the resource pack to the given URL (ZIP)
    #     -> Use 'none' as authorization if no authorization
    # -> into:folderName
    #     -> Writes the resource pack as files into the given
    #        folder name, if it doesn't start with '/', it will
    #        be inside the plugin (unemojis/) folder, if it
    #        starts with '@', it will be inside the plugins folder
    #        Examples:
    #        -> @OtherPlugin/resourcepack
    #        -> /home/user/server/resourcepack/
    #        -> resourcepack
    # -> mcpacks
    #     -> Uses https://mc-packs.net/ to upload the result,
    #        it's a free resource-pack host, you can donate to
    #        them :)
    export: "mcpacks"

format:

    # Configuration for when running on a Paper server
    paper:
        emoji: '<white><emoji> <gray>:<emojiname>: <#ff8df8>/emojis'

    # Configuration for when not running on a Paper server
    legacy:
        # Initial message color, because we can't get it
        # from other plugins using AsyncPlayerChatEvent
        color: '7'

        # Using components in legacy servers can affect
        # compatibility with other plugins since we need
        # to surround the chat event
        rich: true

        # Event surrounding strategy, 'clearRecipients'
        # will remove all event recipients (it makes it
        # compatible with DiscordSRV), 'cancel' will just
        # cancel the event, both strategies may cause problems
        # with another plugins
        surround: 'clearRecipients'

compat:
    # LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    listener-priority: 'HIGHEST'

messages:
    help: |-
        &d/emojis update <id> &8- &7Import emojis from https://unnamed.team/emojis
        &d/emojis reload &8- &7Reload emojis from the emojis.mcemoji file
    list:
        hover: '&f<emoji> &8:<emojiname>:'

#feature:
#    # Tab-completion uses client-side fake-players to
#    # work, it may be buggy (still in development, you
#    # can help by enabling this and reporting any bug
#    # to our support server https://discord.gg/xbba2fy)
#    tab-completion: false