##
##                                           /$$
##                                          |__/
##      /$$$$$$  /$$$$$$/$$$$   /$$$$$$  /$$ /$$  /$$$$$$$
##     /$$__  $$| $$_  $$_  $$ /$$__  $$|__/| $$ /$$_____/
##    | $$$$$$$$| $$ \ $$ \ $$| $$  \ $$ /$$| $$|  $$$$$$
##    | $$_____/| $$ | $$ | $$| $$  | $$| $$| $$ \____  $$
##    |  $$$$$$$| $$ | $$ | $$|  $$$$$$/| $$| $$ /$$$$$$$/
##     \_______/|__/ |__/ |__/ \______/ | $$|__/|_______/
##          plugin by unnamed      /$$  | $$
##                                |  $$$$$$/
##                                 \______/
##

#
# Welcome to the emojis configuration!
#
#
#  -  If you want to use special characters in the config file, you need
#     to save the file using UTF-8, not ANSI or any other encoding
#
#
# If you need help with the configuration, feel free to contact us on
#  -    Discord: https://discord.gg/xbba2fy
#

format:

    # The text displayed when the player hovers an emoji
    # in a player message. Available placeholders:
    # - <emoji>: The Emoji character itself
    # - <emojiname>: The Emoji name
    hover:
        # Format to use when MiniMessage is supported by the server (Paper 1.18+)
        # If not specified, it uses the legacy ampersand formatting
        # mini-message: '<emoji> <gray>:<emojiname>: <#ff8df8>/emojis'

        # Format to use by default (Spigot, Paper 1.17 and olders)
        # Uses the legacy ampersand formatting
        legacy: '&f<emoji> &7:<emojiname>: &d/emojis'

    # Configuration for when not running on a Paper server
    legacy:
        # Initial message prefix, because we can't obtain it
        # from other plugins when using AsyncPlayerChatEvent
        message-prefix: '&f'

        # Using components in legacy servers can affect
        # compatibility with other plugins since we need
        # to surround the chat event
        rich: false

        # Event surrounding strategy, 'clearRecipients'
        # will remove all event recipients (it makes it
        # compatible with DiscordSRV), 'cancel' will just
        # cancel the event, both strategies may cause problems
        # with another plugins
        surround: 'clearRecipients'

compat:
    # LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    use-paper-listener: false
    listener-priority: 'HIGHEST'

messages:
    help: |-
        &8----------------- &dµŋemojis &8- &7Help Page &8-----------------
        &8 - &d/emojis update <id> &8- &7Import emojis from https://unnamed.team/emojis
        &8 - &d/emojis list [page] &8- &7List all emojis
        &8 - &d/emojis reload &8- &7Reload emojis from the emojis.mcemoji file
        &8-----------------------------------------------------
    list:
        invalid-page: '&cInvalid page number!'
        header: '&8----------------- &dµŋemojis &8- &7Page <page> / <maxpages> &8-----------------'
        element:
            available:
                content: '&f<emoji>'
                hover: '&f<emoji> &8:<emojiname>:'
            unavailable:
                content: '&7<emoji>'
                hover: |-
                    &cBuy VIP to unlock this emoji!
                      &7<emoji> &8:<emojiname>:
        show-unavailable: false
        separation:
            1: ' '
            10: '\n'
        max-emojis-per-page: 30
        footer: '&8-----------------------------------------------------'