pack:
    meta:
        write: true
        # The resource-pack icon (in the plugin folder)
        icon: 'icon.png'
        # The resource-pack description
        description: 'Custom server pack'
    # How to generate the resource pack
    # -> file:filename
    #     -> Generates a resource pack as a file (ZIP)
    # -> mergezipfile:filename
    #     -> Similar to file:filename but if the file exists,
    #        it will merge the contents instead of overwriting
    #        them (ZIP)
    # -> upload:authorization:url
    #     -> Uploads the resource pack to the given URL (ZIP)
    #     -> Use 'none' as authorization if no authorization
    # -> into:folderName
    #     -> Writes the resource pack as files into the given
    #        folder name, if it doesn't start with '/', it will
    #        be inside the plugin (unemojis/) folder, if it
    #        starts with '@', it will be inside the plugins folder
    #        Examples:
    #        -> @OtherPlugin/resourcepack
    #        -> /home/user/server/resourcepack/
    #        -> resourcepack
    # -> mcpacks
    #     -> Uses https://mc-packs.net/ to upload the result,
    #        it's a free resource-pack host, you can donate to
    #        them :)
    export: "mcpacks"

format:

    # Configuration for when running on a Paper server
    paper:
        emoji: '<white><emoji> <gray>:<emojiname>: <#ff8df8>/emojis'

    # Configuration for when not running on a Paper server
    legacy:
        # Initial message color, because we can't get it
        # from other plugins using AsyncPlayerChatEvent
        color: 'f'

        # Using components in legacy servers can affect
        # compatibility with other plugins since we need
        # to surround the chat event
        rich: false

        # Event surrounding strategy, 'clearRecipients'
        # will remove all event recipients (it makes it
        # compatible with DiscordSRV), 'cancel' will just
        # cancel the event, both strategies may cause problems
        # with another plugins
        surround: 'clearRecipients'

compat:
    # LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
    use-paper-listener: false
    listener-priority: 'HIGHEST'

messages:
    help: |-
        &8----------------- &dµŋemojis &8- &7Help Page &8-----------------
        &8 - &d/emojis update <id> &8- &7Import emojis from https://unnamed.team/emojis
        &8 - &d/emojis reload &8- &7Reload emojis from the emojis.mcemoji file
        &8-----------------------------------------------------
    list:
        hover: '&f<emoji> &8:<emojiname>:'
    kick: "&dµŋemojis &8| &cError &8| &7You must accept the server resource-pack to join the server"
    warn: "&dµŋemojis &8| &eWarn &8| &7This server supports emojis, enable the server resource-pack to see them!"
    fail: "&dµŋemojis &8| &cError &8| &7Resource pack download failed, try to reconnect."


feature:
    # require-pack is if the player NEEDS to accept the resourcepack.
    # If the pack is required it will kick players who decline or fail to download it.
    # If the pack isnt required they will get a warning instead.
    require-pack: false

application:
    # Message shown on a player first join, they are asked to use the
    # resource pack. This feature is only available if server version
    # is 1.17 or superior
    #
    # You can remove this option
    prompt: '&dµŋemojis &8| &aInfo &8| &7Please accept our resource-pack to enjoy the full experience!'