pack:
    meta:
        write: true
        # The resource-pack icon (in the plugin folder)
        icon: 'icon.png'
        # The resource-pack description
        description: 'Custom server pack'
    export:
        file:
            do: true
            merge: false
            target: 'un-emojis-generated.zip'
        upload:
            do: false
            authorization: 'authorization'
            target: 'https://artemis.unnamed.team/files/upload/testserver'
            apply: false

format:

    # Configuration for when running on a Paper server
    paper:
        emoji: '<white><emoji> <gray>:<emojiname>: <#ff8df8>/emojis'

    # Configuration for when not running on a Paper server
    legacy:
        # Using components in legacy servers can affect
        # compatibility with other plugins since we need
        # to surround the chat event
        rich: true

        # Event surrounding strategy, 'clearRecipients'
        # will remove all event recipients (it makes it
        # compatible with DiscordSRV), 'cancel' will just
        # cancel the event, both strategies may cause problems
        # with another plugins
        surround: 'clearRecipients'

#feature:
#    # Tab-completion uses client-side fake-players to
#    # work, it may be buggy (still in development, you
#    # can help by enabling this and reporting any bug
#    # to our support server https://discord.gg/xbba2fy)
#    tab-completion: false