main: team.unnamed.emojis.EmojisPlugin
name: unemojis
api-version: 1.13
version: 0.1.8
description: Unnamed Team's Emojis Plugin
authors: [Yusshu]
softdepend: [PlaceholderAPI, EzChat]
commands:
    emojis:
        description: Main command for the unEmojis plugin
        usage: /<command> update <id>
