main: team.unnamed.emojis.EmojisPlugin
name: unemojis
version: ${project.version}
api-version: 1.13
description: Unnamed Team's Emojis Plugin
author: Unnamed Team
depend: [creative-central]
softdepend: [PlaceholderAPI, EzChat, TownyChat, DiscordSRV, LPC]
commands:
    emojis:
        description: Main command for the unemojis plugin
        usage: /<command> update <id>