main: team.unnamed.emojis.EmojisPlugin
name: unemojis
api-version: 1.13
version: @version@
description: Unnamed Team's Emojis Plugin
author: UnnamedTeam
softdepend: [PlaceholderAPI, EzChat, TownyChat, DiscordSRV]
commands:
    emojis:
        description: Main command for the unEmojis plugin
        usage: /<command> update <id>
